manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/LOWPROKB
    - name: Kikangh
      url-base: https://github.com/Kikangh/
  projects:
    - name: zmk
      remote: Kikangh
      revision: Kikangh/main
      import: app/west.yml
  self:
    path: config