manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/LOWPROKB
    - name: kikangh
      url-base: https://github.com/Kikangh
  projects:
    - name: zmk
      remote: kikangh
      revision: zenV2-HM_tweaks-Mouse-Display-tweaks-norefactor
      import: app/west.yml
  self:
    path: config