manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/LOWPROKB
    - name: kikangh
      url-base: https://github.com/Kikangh
  projects:
    - name: zmk
      remote: kikangh
      revision: Corneish_zen_v2-Mouse_HM-Tweaks
      import: app/west.yml
  self:
    path: config